/**
 * Shared Pages Function handler for locale-specific destination routing.
 *
 * Two thin route adapters delegate here:
 *   - functions/destinations/[id].js   -> /destinations/:id        (en)
 *   - functions/ja/destinations/[id].js -> /ja/destinations/:id    (ja)
 *
 * KAI-68: serves prerendered HTML for published destinations, the locale's
 * SPA shell with `noindex, follow` for other public destinations, and a real
 * 404 (noindex) for unknown or removed destination ids. Pages Functions take
 * precedence over _redirects, so the `/* /index.html 200` fallback never
 * masks the 404.
 *
 * The manifest (dist/data/kai68-public-destinations.json) is generated by
 * scripts/generate-seo-outputs.ts from the same catalogue the SPA loads, so
 * function and app always agree on what is public.
 *
 * Note: _headers does NOT apply to Function responses; SECURITY headers are
 * set here (see src/seo/meta.ts) and must be kept in sync with public/_headers.
 */
import { routeDestinationRequest } from "../src/seo/router.js";
import { SECURITY_HEADERS } from "../src/seo/meta.js";

const MANIFEST_PATH = "/data/kai68-public-destinations.json";

let manifestCache = null;

/** ASSETS.fetch requires an absolute URL (relative paths throw in the local
 *  runtime); derive the origin from the incoming request. */
function assetUrl(requestUrl, path) {
  return new URL(path, requestUrl).toString();
}

async function loadManifest(env, requestUrl) {
  if (manifestCache) return manifestCache;
  const response = await env.ASSETS.fetch(assetUrl(requestUrl, MANIFEST_PATH));
  if (!response.ok) return null;
  manifestCache = await response.json();
  return manifestCache;
}

/** Creates the onRequest handler for one locale. */
export function createDestinationHandler(locale) {
  return async function onRequest(context) {
    const { id } = context.params;
    const requestUrl = context.request.url;
    if (typeof id !== "string" || !/^[a-z0-9-]{1,128}$/.test(id)) {
      const headers = new Headers(SECURITY_HEADERS);
      headers.set("X-Robots-Tag", "noindex, follow");
      return new Response("Not Found", {
        status: 404,
        headers,
      });
    }

    const manifest = await loadManifest(context.env, requestUrl);
    if (!manifest) {
      // Fail closed when the generated manifest is unavailable. Without it,
      // every arbitrary destination id would receive a Function-rendered SPA
      // shell and scanners could amplify ASSETS work during a bad deploy.
      const headers = new Headers(SECURITY_HEADERS);
      headers.set("Content-Type", "application/json; charset=utf-8");
      headers.set("X-Robots-Tag", "noindex, nofollow");
      headers.set("Retry-After", "60");
      return Response.json(
        { ok: false, error: "destination_manifest_unavailable" },
        { status: 503, headers },
      );
    }

    const result = await routeDestinationRequest({
      id,
      manifest,
      locale,
      fetchAsset: (path) =>
        context.env.ASSETS.fetch(assetUrl(requestUrl, path)),
    });

    const baseHeaders = {
      ...SECURITY_HEADERS,
      ...result.headers,
    };

    if (result.body !== undefined) {
      return new Response(result.body, {
        status: result.status,
        headers: {
          ...baseHeaders,
          "Content-Type": "text/html; charset=utf-8",
        },
      });
    }

    const asset = await context.env.ASSETS.fetch(
      assetUrl(requestUrl, result.assetPath),
    );
    return new Response(asset.body, {
      status: result.status,
      headers: {
        ...baseHeaders,
        "Content-Type": "text/html; charset=utf-8",
      },
    });
  };
}
