import type { Destination } from "@/shared/types/destination";

const prefectureNames: Record<string, string> = {
  Hokkaido: "北海道",
  Aomori: "青森県",
  Iwate: "岩手県",
  Miyagi: "宮城県",
  Akita: "秋田県",
  Yamagata: "山形県",
  Fukushima: "福島県",
  Ibaraki: "茨城県",
  Tochigi: "栃木県",
  Gunma: "群馬県",
  Saitama: "埼玉県",
  Chiba: "千葉県",
  Tokyo: "東京都",
  Kanagawa: "神奈川県",
  Niigata: "新潟県",
  Toyama: "富山県",
  Ishikawa: "石川県",
  Fukui: "福井県",
  Yamanashi: "山梨県",
  Nagano: "長野県",
  Gifu: "岐阜県",
  Shizuoka: "静岡県",
  Aichi: "愛知県",
  Mie: "三重県",
  Shiga: "滋賀県",
  Kyoto: "京都府",
  Osaka: "大阪府",
  Hyogo: "兵庫県",
  Nara: "奈良県",
  Wakayama: "和歌山県",
  Tottori: "鳥取県",
  Shimane: "島根県",
  Okayama: "岡山県",
  Hiroshima: "広島県",
  Yamaguchi: "山口県",
  Tokushima: "徳島県",
  Kagawa: "香川県",
  Ehime: "愛媛県",
  Kochi: "高知県",
  Fukuoka: "福岡県",
  Saga: "佐賀県",
  Nagasaki: "長崎県",
  Kumamoto: "熊本県",
  Oita: "大分県",
  Miyazaki: "宮崎県",
  Kagoshima: "鹿児島県",
  Okinawa: "沖縄県",
};

type MunicipalityKind = Exclude<Destination["kind"], undefined>;

const municipalSuffixes: Partial<Record<MunicipalityKind, string>> = {
  city: "市",
  ward: "区",
  town: "町",
  village: "村",
};

const japaneseLabels: Record<string, string> = {
  Kanto: "関東",
  Kansai: "関西",
  Chubu: "中部",
  Tohoku: "東北",
  Hokkaido: "北海道",
  Chugoku: "中国地方",
  Shikoku: "四国",
  Kyushu: "九州",
  Okinawa: "沖縄",
  Museum: "博物館",
  Tower: "タワー",
  Landmark: "ランドマーク",
  History: "歴史",
  Nature: "自然",
  Food: "グルメ",
  Shopping: "ショッピング",
  Waterfront: "ウォーターフロント",
  Couple: "カップル",
  Family: "家族",
  Photography: "写真",
  Value: "コスパ",
  Walkability: "歩きやすさ",
  Accessibility: "バリアフリー",
  "History & Culture": "歴史・文化",
  Relaxation: "リラックス",
  Spring: "春",
  Summer: "夏",
  Autumn: "秋",
  Winter: "冬",
  "Rainy Day": "雨の日",
  "Travel Hub": "旅行ハブ",
  "City Hub": "都市ハブ",
  "Special Ward": "特別区",
  // Destination `kind` values (lowercase, rendered capitalized on cards)
  aquarium: "水族館",
  beach: "海岸",
  bridge: "橋",
  castle: "城",
  city: "市",
  district: "街並",
  garden: "庭園",
  market: "市場",
  mountain: "山",
  museum: "博物館",
  park: "公園",
  shopping: "買い物",
  shrine: "神社",
  street: "街路",
  temple: "寺院",
  tower: "タワー",
  town: "町",
  ward: "区",
  zoo: "動物園",
  // Common Kanto destination tags (first-position / category-like)
  Culture: "文化",
  Indoor: "屋内",
  "UNESCO World Heritage": "ユネスコ世界遺産",
  Hiking: "ハイキング",
  "Theme Park": "テーマパーク",
  Animals: "動物",
  Anime: "アニメ",
  Waterfalls: "滝",
  Lighthouse: "灯台",
  Viewpoint: "展望",
  Onsen: "温泉",
  "Date Spot": "デートスポット",
  "Digital Art": "デジタルアート",
  Iconic: "象徴的",
  Gardens: "庭園",
  Parks: "公園",
  Temples: "寺院",
  Shrines: "神社",
  Coast: "海岸",
  Coastline: "海岸線",
  Ocean: "海",
  River: "川",
  Lake: "湖",
  Valley: "渓谷",
  Valleys: "渓谷",
  Canal: "運河",
  Island: "島",
  Flowers: "花",
  "Cherry Blossoms": "桜",
  "Plum Blossoms": "梅",
  Foliage: "紅葉",
  Forest: "森",
  "Forest Therapy": "森林セラピー",
  Wildlife: "野生動物",
  "Night View": "夜景",
  "Night Illumination": "夜のライトアップ",
  Illumination: "ライトアップ",
  "Observation Deck": "展望台",
  Panoramas: "パノラマ",
  Photogenic: "映え",
  Romance: "ロマンス",
  Luxury: "高級",
  Upscale: "高級",
  Traditional: "伝統的",
  Historic: "歴史的",
  Historical: "歴史的",
  "Historic Architecture": "歴史的建築",
  "Modern Architecture": "近代建築",
  Architecture: "建築",
  Art: "アート",
  Design: "デザイン",
  Science: "科学",
  Entertainment: "エンタメ",
  Dining: "グルメ",
  Cafes: "カフェ",
  "Street Food": "屋台料理",
  Seafood: "海鮮",
  "Soba Noodles": "蕎麦",
  "Ramen Street": "ラーメン横丁",
  Brewery: "醸造所",
  Beer: "ビール",
  "Factory Tour": "工場見学",
  "Railway Museum": "鉄道博物館",
  Railway: "鉄道",
  Horology: "時計",
  Bonsai: "盆栽",
  Stationery: "文房具",
  Manga: "マンガ",
  "Anime Pilgrimage": "アニメ聖地",
  "Pop Culture": "ポップカルチャー",
  "Showa Retro": "昭和レトロ",
  Edo: "江戸",
  "Little Edo": "小江戸",
  Pilgrimage: "巡礼",
  "Tokugawa Ieyasu": "徳川家康",
  "Takeda Shingen": "武田信玄",
  "Kodokan School": "弘道館",
  "Kengo Kuma": "隈研吾",
  "Arata Isozaki": "磯崎新",
  "Mito Tokugawa": "水戸徳川",
  "Meiji Jingu": "明治神宮",
  "Nikko Toshogu": "日光東照宮",
  "Shogunate Seat": "幕府の所在地",
  "Samurai Palace": "御殿",
  "Honmaru Goten": "本丸御殿",
  "Fujimi-yagura": "富士見櫓",
  "Otemon Gate": "大手門",
  "Dry Moats": "空堀",
  "Earthen Fortification": "土塁",
  "Moat Ruins": "堀跡",
  "Stone Steps": "石段",
  Lanterns: "提灯",
  "Active Hiking": "ハイキング",
  Climbing: "登山",
  Biking: "サイクリング",
  Cycling: "サイクリング",
  Boating: "ボート",
  Surfing: "サーフィン",
  Walking: "散歩",
  "Walk-heavy": "徒歩中心",
  "Road Trip": "ドライブ",
  Drive: "ドライブ",
  Sports: "スポーツ",
  Baseball: "野球",
  "Thrill Rides": "絶叫アトラクション",
  Rollercoasters: "ジェットコースター",
  "Amusement Park": "遊園地",
  "Fastest Elevator": "日本最速エレベーター",
  Action: "体験",
  Active: "アクティブ",
  Escapes: "逃避",
  "Winter getaway": "冬の逃避",
  Seasonal: "季節",
  "Seasonal Flowers": "季節の花",
  "Family Friendly": "家族向け",
  "Family-friendly": "家族向け",
  Free: "無料",
  "Free Observatory": "無料展望台",
  "World's Tallest Tower": "世界一高い塔",
  "Japan's Top Castles": "日本の名城",
  "Top 100 Castle": "日本100名城",
  "Three Great Gardens": "日本三名園",
  "Three Great Views": "日本三景",
  "Three Great Waterfalls": "日本三名瀑",
  "Three Great Buddhas": "日本三大仏",
  "Three Great Jingu": "日本三大神宮",
  "Japan's Three Great Cherry Trees": "日本三大桜",
  "National Natural Monument": "天然記念物",
  "National Treasure": "国宝",
  "12 Original Keeps": "現存十二天守",
  "National Museum": "国立博物館",
  "Treasure Museum": "宝物館",
  "Interactive Museum": "体験型ミュージアム",
  "Historic Zoo": "歴史的動物園",
  "Botanical Gardens": "植物園",
  "Spacious Park": "広々とした公園",
  "Imperial Gardens": "御庭",
  "Historical Park": "歴史公園",
  Underground: "地下",
  "Indoor Lawn": "屋内芝生",
  "Indoor Park": "屋内遊園地",
  Insectarium: "昆虫館",
  Panda: "パンダ",
  "Giant Statue": "大像",
  "Lion Bus": "ライオンバス",
  "Fuji Views": "富士の眺め",
  "Mt Fuji View": "富士の眺め",
  "Mount Fuji View": "富士の眺望",
  "Fuji-Q": "富士急",
  "Fuji Base": "富士の麓",
  "Pacific Ocean": "太平洋",
  "Tokyo Bay View": "東京ベイの眺め",
  "Port View": "港湾の眺め",
  "Ocean View": "海の眺め",
  "Hill Views": "丘の眺め",
  "Cliff Views": "崖の眺め",
  "Peak Views": "山頂の眺め",
  "Deck Views": "展望デッキ",
  "Sky Edge": "スカイエッジ",
  "Open-Air Glass Edge": "屋外ガラスの縁",
  "Mirror Glass": "ミラーガラス",
  "Triangular Glass": "三角ガラス",
  "Helix Geometry": "らせん幾何",
  "Glass Geometry": "ガラス幾何",
  "Record Breaking": "世界記録",
  "World Record": "世界記録",
  "202m Height": "高さ202m",
  "229m Rooftop": "屋上229m",
  "251m Sky Park": "スカイパーク251m",
  "270m Sky Deck": "スカイデッキ270m",
  "273m Height": "高さ273m",
  "Eiffel-Inspired": "エッフェル霊感",
  "Scramble Crossing": "スクランブル交差点",
  "Roppongi Hills": "六本木ヒルズ",
  "Mori Art Museum": "森美術館",
  Solamachi: "ソラマチ",
  "Ikebukuro Skyline": "池袋のスカイライン",
  "Shinjuku Skyline": "新宿のスカイライン",
  "Minato Mirai View": "みなとみらいの眺め",
  "Shibuya Scramble View": "渋谷スクランブルの眺め",
  "Shibuya Ward": "渋谷区",
  "Shinkansen Hub": "新幹線の拠点",
  "Yamanote Line": "山手線",
  Monorail: "モノレール",
  "Imperial Capital": "古都",
  "Kyoto City": "京都市",
  "Osaka City": "大阪市",
  Dotonbori: "道頓堀",
  "Kuromon Market": "黒門市場",
  "Takoyaki Capital": "たこ焼きの本場",
  "War Memorial": "戦争記念施設",
  "Peace Memorial": "平和記念施設",
  Peace: "平和",
  "UNESCO Area": "世界遺産エリア",
  "Scenic Rail": "景観鉄道",
  Scenic: "絶景",
  Steam: "噴気",
  Owakudani: "大涌谷",
  "Lake Ashi": "芦ノ湖",
  "Lake Chuzenji Outlet": "中禅寺湖の流出",
  "River Gorge": "渓谷",
  "River Blue": "青い川",
  "Gorge hikes": "渓谷ハイキング",
  "Five-Tier Falls": "五段の滝",
  Marshlands: "湿地帯",
  "Granite peaks": "花崗岩の峰",
  "Winter Frozen": "冬季氷結",
  Museums: "博物館",
  Village: "村",
  Urban: "都市",
  Quiet: "静寂",
  Unique: "ユニーク",
  "Regional Hub": "地域の拠点",
  "Pagoda View": "塔の眺め",
  "Tenbou Park": "展望公園",
  "Edo Wonderland": "江戸ワンダーランド",
};

export function formatPrefecture(prefecture: string, locale: "en" | "ja") {
  return locale === "ja"
    ? (prefectureNames[prefecture] ?? prefecture)
    : prefecture;
}

export function localizePlaceLabel(value: string, locale: "en" | "ja") {
  return locale === "ja" ? (japaneseLabels[value] ?? value) : value;
}

/** Use official Japanese municipality suffixes without duplicating them. */
export function formatPlaceName(
  place: Pick<Destination, "kind" | "name">,
  locale: "en" | "ja",
) {
  if (locale !== "ja") return place.name;
  const suffix = place.kind ? municipalSuffixes[place.kind] : undefined;
  if (!suffix || !/[\u3040-\u30ff\u3400-\u9fff]/.test(place.name)) {
    return place.name;
  }
  return place.name.endsWith(suffix) ? place.name : `${place.name}${suffix}`;
}
