import type { Destination } from "@/shared/types/destination";

const prefectureNames: Record<string, string> = {
  Hokkaido: "北海道",
  Aomori: "青森県",
  Iwate: "岩手県",
  Miyagi: "宮城県",
  Akita: "秋田県",
  Yamagata: "山形県",
  Fukushima: "福島県",
  Ibaraki: "茨城県",
  Tochigi: "栃木県",
  Gunma: "群馬県",
  Saitama: "埼玉県",
  Chiba: "千葉県",
  Tokyo: "東京都",
  Kanagawa: "神奈川県",
  Niigata: "新潟県",
  Toyama: "富山県",
  Ishikawa: "石川県",
  Fukui: "福井県",
  Yamanashi: "山梨県",
  Nagano: "長野県",
  Gifu: "岐阜県",
  Shizuoka: "静岡県",
  Aichi: "愛知県",
  Mie: "三重県",
  Shiga: "滋賀県",
  Kyoto: "京都府",
  Osaka: "大阪府",
  Hyogo: "兵庫県",
  Nara: "奈良県",
  Wakayama: "和歌山県",
  Tottori: "鳥取県",
  Shimane: "島根県",
  Okayama: "岡山県",
  Hiroshima: "広島県",
  Yamaguchi: "山口県",
  Tokushima: "徳島県",
  Kagawa: "香川県",
  Ehime: "愛媛県",
  Kochi: "高知県",
  Fukuoka: "福岡県",
  Saga: "佐賀県",
  Nagasaki: "長崎県",
  Kumamoto: "熊本県",
  Oita: "大分県",
  Miyazaki: "宮崎県",
  Kagoshima: "鹿児島県",
  Okinawa: "沖縄県",
};

type MunicipalityKind = Exclude<Destination["kind"], undefined>;

const municipalSuffixes: Partial<Record<MunicipalityKind, string>> = {
  city: "市",
  ward: "区",
  town: "町",
  village: "村",
};

const japaneseLabels: Record<string, string> = {
  // Canonical taxonomy ids are display labels too; keep lowercase values
  // explicit so a new id cannot silently fall back to English.
  aizu: "会津",
  aomori: "青森",
  animals: "動物",
  architecture: "建築",
  archaeology: "考古学",
  art: "アート",
  basho: "芭蕉",
  bandai: "磐梯",
  beppu: "別府",
  caldera: "カルデラ",
  cape: "岬",
  cave: "洞窟",
  cobalt: "コバルト",
  crater: "火口",
  cruise: "クルーズ",
  drive: "ドライブ",
  ehime: "愛媛",
  engineering: "工学",
  event: "イベント",
  fukui: "福井",
  fukushima: "福島",
  fuji: "富士",
  gorge: "渓谷",
  hyogo: "兵庫",
  iwate: "岩手",
  kagawa: "香川",
  kagoshima: "鹿児島",
  kochi: "高知",
  kumamoto: "熊本",
  miyagi: "宮城",
  nebuta: "ねぶた",
  niigata: "新潟",
  oita: "大分",
  religion: "宗教",
  sanriku: "三陸",
  shikoku: "四国",
  station: "駅",
  tohoku: "東北",
  tokushima: "徳島",
  tottori: "鳥取",
  volcano: "火山",
  yamagata: "山形",
  yamaguchi: "山口",
  yamanashi: "山梨",
  "Aichi Travel": "愛知旅行",
  "Chiba Travel": "千葉旅行",
  "Ehime Travel": "愛媛旅行",
  "Fukuoka Travel": "福岡旅行",
  "Gifu Travel": "岐阜旅行",
  "Gunma Travel": "群馬旅行",
  "Hiroshima Travel": "広島旅行",
  "Hokkaido Travel": "北海道旅行",
  "Hyogo Travel": "兵庫旅行",
  "Ibaraki Travel": "茨城旅行",
  "Japan Travel": "日本旅行",
  "Kagawa Travel": "香川旅行",
  "Kanagawa Travel": "神奈川旅行",
  "Kagoshima Travel": "鹿児島旅行",
  "Kyoto Travel": "京都旅行",
  "Kochi Travel": "高知旅行",
  "Kumamoto Travel": "熊本旅行",
  "Miyazaki Travel": "宮崎旅行",
  "Nagasaki Travel": "長崎旅行",
  "Nagano Travel": "長野旅行",
  "Nara Travel": "奈良旅行",
  "Oita Travel": "大分旅行",
  "Okayama Travel": "岡山旅行",
  "Osaka Travel": "大阪旅行",
  "Saga Travel": "佐賀旅行",
  "Saitama Travel": "埼玉旅行",
  "Shiga Travel": "滋賀旅行",
  "Shimane Travel": "島根旅行",
  "Shizuoka Travel": "静岡旅行",
  "Tochigi Travel": "栃木旅行",
  "Tokushima Travel": "徳島旅行",
  "Tottori Travel": "鳥取旅行",
  "Tokyo Travel": "東京旅行",
  "Wakayama Travel": "和歌山旅行",
  "Yamaguchi Travel": "山口旅行",
  "Yamanashi Travel": "山梨旅行",
  "Architecture & History": "建築と歴史",
  Cities: "都市",
  Education: "教育",
  Foodie: "グルメ好き",
  "Free Admission": "入場無料",
  "Free admission": "入場無料",
  Hub: "拠点",
  "Historic Site": "史跡",
  "Historic Street": "歴史的な通り",
  "Local Food": "ご当地グルメ",
  "Traditional Craft": "伝統工芸",
  "Zoo & Botanical": "動物園と植物園",
  "12 Original Keeps": "現存十二天守",
  "202m Height": "高さ202m",
  "229m Rooftop": "屋上229m",
  "251m Sky Park": "スカイパーク251m",
  "270m Sky Deck": "スカイデッキ270m",
  "273m Height": "高さ273m",
  Accessibility: "バリアフリー",
  Action: "体験",
  Active: "アクティブ",
  "Active Hiking": "ハイキング",
  "Amusement Park": "遊園地",
  Animals: "動物",
  Anime: "アニメ",
  "Anime Pilgrimage": "アニメ聖地",
  Aquarium: "水族館",
  "Arata Isozaki": "磯崎新",
  Arcade: "アーケード",
  Architecture: "建築",
  Art: "アート",
  "Art & Architecture": "アートと建築",
  "Art & Culture": "アートと文化",
  "Art Museum": "美術館",
  Attraction: "アトラクション",
  Autumn: "秋",
  Baseball: "野球",
  Bay: "湾",
  Beach: "ビーチ",
  Beaches: "ビーチ",
  Beer: "ビール",
  Biking: "サイクリング",
  "Boat Tour": "船上クルーズ",
  Boating: "ボート",
  Bonsai: "盆栽",
  "Botanical Gardens": "植物園",
  Brewery: "醸造所",
  Bridge: "橋",
  "Bridge View": "橋の眺め",
  "Bronze Statue": "ブロンズ像",
  Business: "ビジネス",
  Cafes: "カフェ",
  Caldera: "カルデラ",
  Canal: "運河",
  Canals: "運河",
  Cape: "岬",
  Castle: "城",
  "Castles & History": "城と歴史",
  Cave: "洞窟",
  Caves: "洞窟",
  Cedar: "杉",
  Cenotaph: "慰霊碑",
  "Cherry Blossom": "桜",
  "Cherry Blossoms": "桜",
  Chinatown: "チャイナタウン",
  Chubu: "中部",
  Chugoku: "中国地方",
  City: "市街",
  "City Hub": "都市ハブ",
  "City View": "市街の眺め",
  "Cliff Views": "崖の眺め",
  Cliffs: "断崖",
  Climbing: "登山",
  Coast: "海岸",
  Coastal: "沿岸",
  Coastline: "海岸線",
  Coral: "珊瑚",
  Couple: "カップル",
  Crafts: "工芸",
  Crater: "火口",
  Cruise: "クルーズ",
  Culinary: "料理",
  "Cultural Property": "文化財",
  Culture: "文化",
  "Culture & Castles": "文化と城",
  "Culture & History": "文化と歴史",
  "Culture & Museums": "文化とミュージアム",
  "Culture & Temples": "文化と寺院",
  Cycling: "サイクリング",
  Dam: "ダム",
  Dance: "ダンス",
  "Date Spot": "デートスポット",
  "Deck Views": "展望デッキ",
  Deer: "鹿",
  Design: "デザイン",
  "Digital Art": "デジタルアート",
  Dining: "グルメ",
  Dinosaurs: "恐竜",
  District: "地区",
  Dotonbori: "道頓堀",
  Drive: "ドライブ",
  "Dry Moats": "空堀",
  "Earthen Fortification": "土塁",
  Edo: "江戸",
  "Edo Wonderland": "江戸ワンダーランド",
  Eel: "うなぎ",
  "Eiffel-Inspired": "エッフェル霊感",
  Electronics: "電子機器",
  Engineering: "工学",
  Entertainment: "エンタメ",
  Escapes: "逃避",
  Event: "イベント",
  Experience: "体験",
  "Factory Tour": "工場見学",
  Family: "家族",
  "Family & Kids": "ファミリー・キッズ",
  "Family Friendly": "家族向け",
  "Family-friendly": "家族向け",
  Farm: "農場",
  Fashion: "ファッション",
  "Fastest Elevator": "日本最速エレベーター",
  Festival: "祭り",
  Festivals: "祭り",
  "Five-Tier Falls": "五段の滝",
  Float: "山車",
  Flowers: "花",
  Foliage: "紅葉",
  Folkcraft: "民芸",
  Food: "グルメ",
  "Food & Dining": "グルメ・食事",
  Footbaths: "足湯",
  Forest: "森",
  "Forest Therapy": "森林セラピー",
  Free: "無料",
  "Free Observatory": "無料展望台",
  Fruit: "果物",
  Fugu: "ふぐ",
  "Fuji Base": "富士の麓",
  "Fuji Views": "富士の眺め",
  "Fuji-Q": "富士急",
  "Fujimi-yagura": "富士見櫓",
  Gaming: "ゲーム",
  Garden: "庭園",
  Gardens: "庭園",
  Geology: "地質",
  "Giant Statue": "大像",
  "Glass Geometry": "ガラス幾何",
  Gorge: "渓谷",
  "Gorge hikes": "渓谷ハイキング",
  "Granite peaks": "花崗岩の峰",
  Grassland: "草原",
  "Helix Geometry": "らせん幾何",
  Highlands: "高地",
  Hiking: "ハイキング",
  "Hill Views": "丘の眺め",
  Historic: "歴史的",
  "Historic Architecture": "歴史的建築",
  "Historic Zoo": "歴史的動物園",
  Historical: "歴史的",
  "Historical Park": "歴史公園",
  History: "歴史",
  "History & Culture": "歴史・文化",
  Hokkaido: "北海道",
  "Honmaru Goten": "本丸御殿",
  Horology: "時計",
  Horses: "馬",
  "Hot Spring": "温泉",
  "Hot Springs & Wellness": "温泉とウェルネス",
  Houseboats: "屋形船",
  Iconic: "象徴的",
  "Ikebukuro Skyline": "池袋のスカイライン",
  Illumination: "ライトアップ",
  "Imperial Capital": "古都",
  "Imperial Gardens": "御庭",
  Indoor: "屋内",
  "Indoor Lawn": "屋内芝生",
  "Indoor Park": "屋内遊園地",
  Industrial: "産業",
  Insectarium: "昆虫館",
  "Interactive Museum": "体験型ミュージアム",
  Island: "島",
  Islands: "島々",
  "Islands & Beaches": "島とビーチ",
  "Japan's Three Great Cherry Trees": "日本三大桜",
  "Japan's Top Castles": "日本の名城",
  Kansai: "関西",
  Kanto: "関東",
  "Kengo Kuma": "隈研吾",
  "Kodokan School": "弘道館",
  "Kuromon Market": "黒門市場",
  "Kyoto City": "京都市",
  Kyushu: "九州",
  Lake: "湖",
  "Lake Ashi": "芦ノ湖",
  "Lake Chuzenji Outlet": "中禅寺湖の流出",
  "Lake Views": "湖の眺め",
  Landmark: "ランドマーク",
  "Landscape Garden": "庭園",
  Lanterns: "提灯",
  Learning: "学び",
  Leisure: "レジャー",
  Lighthouse: "灯台",
  "Lion Bus": "ライオンバス",
  Literature: "文学",
  "Little Edo": "小江戸",
  Luxury: "高級",
  Manga: "マンガ",
  Marine: "マリン",
  "Marine Life": "海洋生物",
  Maritime: "海事",
  Market: "市場",
  Marshlands: "湿地帯",
  "Meiji Jingu": "明治神宮",
  Memorial: "記念碑",
  "Minato Mirai View": "みなとみらいの眺め",
  "Mirror Glass": "ミラーガラス",
  Mist: "霧",
  "Mito Tokugawa": "水戸徳川",
  "Moat Ruins": "堀跡",
  Modern: "モダン",
  "Modern Architecture": "近代建築",
  "Modern Art": "現代アート",
  Monorail: "モノレール",
  "Mori Art Museum": "森美術館",
  "Mount Fuji View": "富士の眺望",
  Mountain: "山",
  Mountains: "山々",
  "Mt Fuji View": "富士の眺め",
  Museum: "博物館",
  "Museum & Art": "美術館・アート",
  Museums: "博物館",
  Mythology: "神話",
  "National Museum": "国立博物館",
  "National Natural Monument": "天然記念物",
  "National Park": "国立公園",
  "National Treasure": "国宝",
  Nature: "自然",
  "Nature & Gardens": "自然と庭園",
  "Nature & History": "自然と歴史",
  "Nature & Outdoors": "自然とアウトドア",
  "Nature & Parks": "自然と公園",
  Naval: "海軍",
  "Night Illumination": "夜のライトアップ",
  "Night View": "夜景",
  Nightlife: "ナイトライフ",
  "Nikko Toshogu": "日光東照宮",
  Observation: "展望",
  "Observation Deck": "展望台",
  Observatory: "展望台",
  Ocean: "海",
  "Ocean View": "海の眺め",
  Okinawa: "沖縄",
  Onsen: "温泉",
  "Onsen & Wellness": "温泉・ウェルネス",
  "Onsen Town": "温泉街",
  "Open-Air Glass Edge": "屋外ガラスの縁",
  "Open-air": "屋外",
  "Osaka City": "大阪市",
  "Otemon Gate": "大手門",
  Outdoor: "アウトドア",
  Outdoors: "アウトドア",
  Owakudani: "大涌谷",
  "Pacific Ocean": "太平洋",
  "Pagoda View": "塔の眺め",
  Panda: "パンダ",
  Panorama: "パノラマ",
  Panoramas: "パノラマ",
  "Panoramic Bay View": "パノラマの湾の眺め",
  Park: "公園",
  Parks: "公園",
  Peace: "平和",
  "Peace Memorial": "平和記念施設",
  "Peak Views": "山頂の眺め",
  Photogenic: "映え",
  Photography: "写真",
  Pilgrimage: "巡礼",
  "Plum Blossoms": "梅",
  "Pop Culture": "ポップカルチャー",
  Port: "港",
  "Port View": "港湾の眺め",
  "Post Town": "宿場町",
  "Post Towns": "宿場町",
  Pottery: "陶芸",
  "Preserved Streets": "保存された街並み",
  Pristine: "原生",
  "Quasi-National Park": "国定公園",
  Quiet: "静寂",
  Railway: "鉄道",
  "Railway Museum": "鉄道博物館",
  "Rain-friendly": "雨でも楽しめる",
  "Rainy Day": "雨の日",
  "Ramen Street": "ラーメン横丁",
  Ravine: "渓谷",
  "Record Breaking": "世界記録",
  "Regional Hub": "地域の拠点",
  Relaxation: "リラックス",
  Religion: "宗教",
  Remote: "秘境",
  Resort: "リゾート",
  "Ria Coast": "リアス海岸",
  River: "川",
  "River Blue": "青い川",
  "River Gorge": "渓谷",
  "River walks": "川沿いの散策",
  Riverfront: "川沿い",
  "Road Trip": "ドライブ",
  "Rock Formation": "奇岩",
  Rollercoasters: "ジェットコースター",
  Romance: "ロマンス",
  Ropeway: "ロープウェイ",
  "Ropeway Access": "ロープウェイでアクセス",
  "Roppongi Hills": "六本木ヒルズ",
  Rugged: "険しい地形",
  Ruins: "遺跡",
  Ryokan: "旅館",
  "Sake Brews": "酒蔵",
  "Samurai Heritage": "侍文化",
  "Samurai Palace": "御殿",
  "Samurai Town": "侍の町",
  "Sand Bath": "砂蒸し風呂",
  Sandbar: "砂州",
  Scenery: "景観",
  Scenic: "絶景",
  "Scenic Beauty": "景勝地",
  "Scenic Drive": "絶景ドライブ",
  "Scenic Drives & Ocean Views": "絶景ドライブと海の眺め",
  "Scenic Rail": "景観鉄道",
  "Scenic Railway": "景観鉄道",
  Science: "科学",
  "Scramble Crossing": "スクランブル交差点",
  Scuba: "スキューバダイビング",
  Sea: "海",
  "Sea Caves": "海食洞",
  Seafood: "海鮮",
  "Seafood Market": "海鮮市場",
  Seasonal: "季節",
  "Seasonal Flowers": "季節の花",
  Seasons: "季節",
  "Shibuya Scramble View": "渋谷スクランブルの眺め",
  "Shibuya Ward": "渋谷区",
  Shikoku: "四国",
  "Shinjuku Skyline": "新宿のスカイライン",
  "Shinkansen Access": "新幹線アクセス",
  "Shinkansen Hub": "新幹線の拠点",
  "Shogunate Seat": "幕府の所在地",
  Shopping: "ショッピング",
  "Showa Retro": "昭和レトロ",
  Shrine: "神社",
  Shrines: "神社",
  "Shrines & Temples": "神社と寺院",
  Sightseeing: "観光",
  Skiing: "スキー",
  "Sky Edge": "スカイエッジ",
  Skyscraper: "高層ビル",
  Slopes: "斜面",
  Snorkeling: "シュノーケリング",
  Snow: "雪",
  "Snow Wall": "雪の壁",
  "Soba Noodles": "蕎麦",
  Solamachi: "ソラマチ",
  "Spacious Park": "広々とした公園",
  "Special Ward": "特別区",
  Spiritual: "スピリチュアル",
  Sports: "スポーツ",
  Spring: "春",
  Station: "駅",
  Stationery: "文房具",
  Steam: "噴気",
  "Stone Arch": "石のアーチ",
  "Stone Steps": "石段",
  Street: "通り",
  "Street Food": "屋台料理",
  "Strolling Garden": "回遊式庭園",
  "Sulfur baths": "硫黄泉",
  Summer: "夏",
  Sunset: "夕日",
  Surfing: "サーフィン",
  "Takeda Shingen": "武田信玄",
  "Takoyaki Capital": "たこ焼きの本場",
  "Tea Ceremony": "茶道",
  Technology: "テクノロジー",
  Temple: "寺院",
  Temples: "寺院",
  "Tenbou Park": "展望公園",
  Theatre: "劇場",
  "Theme Park": "テーマパーク",
  "Thermal Baths": "温泉",
  "Three Great Buddhas": "日本三大仏",
  "Three Great Gardens": "日本三名園",
  "Three Great Jingu": "日本三大神宮",
  "Three Great Views": "日本三景",
  "Three Great Waterfalls": "日本三名瀑",
  "Thrill Rides": "絶叫アトラクション",
  Tidal: "干満",
  Tohoku: "東北",
  "Tokugawa Ieyasu": "徳川家康",
  "Tokyo Bay View": "東京ベイの眺め",
  "Top 100 Castle": "日本100名城",
  Tower: "タワー",
  Town: "町",
  Traditional: "伝統的",
  Train: "電車",
  Transport: "交通",
  "Travel Hub": "旅行ハブ",
  "Treasure Museum": "宝物館",
  "Triangular Glass": "三角ガラス",
  "Tub Boats": "たらい舟",
  UNESCO: "ユネスコ",
  "UNESCO Area": "世界遺産エリア",
  "UNESCO World Heritage": "ユネスコ世界遺産",
  Underground: "地下",
  Unique: "ユニーク",
  Upscale: "高級",
  Urban: "都市",
  "Urban Hub": "都市ハブ",
  "Urban Ward": "都心区",
  Valley: "渓谷",
  Valleys: "渓谷",
  Value: "コスパ",
  Viewpoint: "展望",
  Viewpoints: "展望スポット",
  "Viewpoints & Photography": "展望と写真",
  Views: "景観",
  Village: "村",
  Volcano: "火山",
  Walk: "散策",
  "Walk-heavy": "徒歩中心",
  Walkability: "歩きやすさ",
  Walking: "散歩",
  "War Memorial": "戦争記念施設",
  "Warehouse Museum": "倉庫ミュージアム",
  "Water purity": "水質",
  Waterfall: "滝",
  Waterfalls: "滝",
  Waterfront: "ウォーターフロント",
  Waterwheel: "水車",
  Wellness: "ウェルネス",
  "Western Architecture": "西洋建築",
  "Whale Shark": "ジンベエザメ",
  "White-Walled Warehouses": "白壁の蔵",
  Wildlife: "野生動物",
  Winter: "冬",
  "Winter Frozen": "冬季氷結",
  "Winter getaway": "冬の逃避",
  "Wooden Bridge": "木橋",
  "World Heritage": "世界遺産",
  "World Record": "世界記録",
  "World's Tallest Tower": "世界一高い塔",
  "Yagura Turrets": "櫓",
  "Yamanote Line": "山手線",
  Zen: "禅",
  Zoo: "動物園",
  amusement_park: "遊園地",
  aquarium: "水族館",
  autumn: "秋",
  beach: "海岸",
  boat: "船",
  bridge: "橋",
  canyon: "峡谷",
  castle: "城",
  cemetery: "墓地",
  "cherry-blossoms": "桜",
  city: "市",
  cliff: "断崖",
  cliffs: "断崖",
  coast: "海岸",
  coastal: "沿岸",
  cultural: "文化的",
  culture: "文化",
  cycling: "サイクリング",
  district: "街並",
  dunes: "砂丘",
  entertainment: "エンターテインメント",
  festival: "祭り",
  flower: "花",
  foxes: "狐",
  garden: "庭園",
  geopark: "ジオパーク",
  geothermal: "地熱",
  hiking: "ハイキング",
  historic: "歴史的",
  "historic town": "歴史的な町",
  historic_town: "歴史的な町",
  history: "歴史",
  island: "島",
  lake: "湖",
  limestone: "石灰岩",
  market: "市場",
  memorial: "記念",
  mixed: "複合",
  monument: "記念碑",
  mountain: "山",
  multicolour: "多色",
  museum: "博物館",
  natural: "自然",
  nature: "自然",
  observation: "展望",
  ocean: "海",
  onsen: "温泉",
  pagoda: "五重塔",
  park: "公園",
  pilgrimage: "巡礼",
  ponds: "池",
  "post town": "宿場町",
  relaxation: "リラックス",
  rock_formation: "奇岩",
  romance: "ロマンス",
  ruins: "遺跡",
  ryokan: "旅館",
  sacred: "神聖",
  samurai: "侍",
  scenic: "景勝",
  sea: "海",
  seasonal: "季節",
  seasons: "季節",
  shopping: "買い物",
  shrine: "神社",
  sightseeing: "観光",
  skiing: "スキー",
  snow: "雪",
  "snow monsters": "樹氷",
  spiritual: "スピリチュアル",
  spring: "春",
  street: "街路",
  summer: "夏",
  temple: "寺院",
  thatched: "茅葺き",
  theme_park: "テーマパーク",
  torii: "鳥居",
  tower: "タワー",
  town: "町",
  underground: "地下",
  unique: "ユニーク",
  valley: "渓谷",
  viewpoint: "展望",
  village: "村",
  volcanic: "火山",
  ward: "区",
  waterfall: "滝",
  winter: "冬",
  wisteria: "藤",
  wooden: "木造",
  zoo: "動物園",
};

export function formatPrefecture(prefecture: string, locale: "en" | "ja") {
  return locale === "ja"
    ? (prefectureNames[prefecture] ?? prefecture)
    : prefecture;
}

export function localizePlaceLabel(value: string, locale: "en" | "ja") {
  return locale === "ja" ? (japaneseLabels[value] ?? value) : value;
}

/** Use official Japanese municipality suffixes without duplicating them. */
export function formatPlaceName(
  place: Pick<Destination, "kind" | "name">,
  locale: "en" | "ja",
) {
  if (locale !== "ja") return place.name;
  const suffix = place.kind ? municipalSuffixes[place.kind] : undefined;
  if (!suffix || !/[\u3040-\u30ff\u3400-\u9fff]/.test(place.name)) {
    return place.name;
  }
  return place.name.endsWith(suffix) ? place.name : `${place.name}${suffix}`;
}
