import fs from "fs";
import path from "path";
import type { Destination } from "../src/shared/types/destination";

const PARENT_BY_DESTINATION_ID: Record<string, string> = {
  // Existing verified relationships
  "shuri-castle-okinawa": "naha-city",
  "kokusai-dori-naha": "naha-city",
  "naminoue-shrine-naha": "naha-city",
  "fukushuen-garden-naha": "naha-city",
  "kouri-island-okinawa": "nago-city",
  "nago-pineapple-park": "nago-city",
  "busena-marine-park-nago": "nago-city",
  "churaumi-aquarium-motobu": "motobu-town",
  "bise-fukugi-tree-road-motobu": "motobu-town",
  "nakijin-castle-ruins-motobu": "motobu-town",
  "kabira-bay-ishigaki": "ishigaki-city",
  "tamatorizaki-viewpoint-ishigaki": "ishigaki-city",
  "yonehara-beach-coral-ishigaki": "ishigaki-city",
  "yonaha-maehama-beach-miyako": "miyakojima-city",
  "irabu-bridge-irabujima-miyako": "miyakojima-city",
  "higashi-hennazaki-cape-miyako": "miyakojima-city",
  "yokohama-chinatown": "yokohama-city",
  "minato-mirai-21-yokohama": "yokohama-city",
  "yamashita-park-yokohama": "yokohama-city",
  "yokohama-red-brick-warehouse": "yokohama-city",
  "sankeien-garden-yokohama": "yokohama-city",
  "cupnoodles-museum-yokohama": "yokohama-city",
  "shin-yokohama-raumen-museum": "yokohama-city",
  "yokohama-landmark-tower-sky-garden": "yokohama-city",
  "yokohama-cosmo-world": "yokohama-city",
  "yokohama-marine-tower": "yokohama-city",
  "osanbashi-pier-yokohama": "yokohama-city",
  "yokohama-hakkeijima-sea-paradise": "yokohama-city",
  "motomachi-shopping-street-yokohama": "yokohama-city",
  "yokohama-zoorasia": "yokohama-city",
  "sensoji-temple-tokyo": "taito-city",
  "tokyo-skytree-sumida": "sumida-city",
  "tokyo-tower-minato": "minato-city",
  "meiji-jingu-shrine-shibuya": "shibuya-city",
  "shibuya-crossing-tokyo": "shibuya-city",
  "tsukiji-outer-market": "chuo-city-tokyo",
  "ginza-district-chuo": "chuo-city-tokyo",
  "shinjuku-gyoen-national-garden": "shinjuku-city",
  "akihabara-electric-town-chiyoda": "chiyoda-city",
  "ueno-park-taito": "taito-city",
  "roppongi-hills-minato": "minato-city",
  "odaiba-entertainment-district": "minato-city",
  "imperial-palace-chiyoda": "chiyoda-city",
  "harajuku-takeshita-street-shibuya": "shibuya-city",

  // New regional mappings verified against municipal boundaries & transport hubs
  "abashiri-drift-ice": "abashiri-city",
  "aizu-samurai-mansion-fukushima": "aizuwakamatsu-city",
  "aoba-castle-museum": "sendai-city",
  "ashikaga-flower-park": "ashikaga-city",
  "aso-kuju-national-park": "aso-city",
  "atsueta-shrine-nagoya": "nagoya-city",
  "beppu-hells": "beppu-city",
  "biei-patchwork-road": "furano-city",
  "bizen-pottery-village": "okayama-city",
  "boso-peninsula": "kisarazu-city",
  "chiran-samurai-residences": "kagoshima-city",
  "chubu-centrair-sky-deck": "nagoya-city",
  "dewa-sanzan-yamagata": "yamagata-city",
  "dogo-onsen": "matsuyama-city",
  "eikando-temple": "kyoto-city",
  "enryaku-ji-shiga": "otsu-city",
  "fujiko-f-fujio-museum": "kawasaki-city",
  "fukuyama-castle": "fukuyama-city",
  "fushimi-inari-taisha": "kyoto-city",
  "fushimi-sake-district": "kyoto-city",
  "gifu-castle": "gifu-city",
  "goryokaku-fort-hakodate": "hakodate-city",
  "gotoku-ji": "setagaya-city",
  "gujo-hachiman-castle": "gifu-city",
  "gunma-ikaho-onsen": "kusatsu-town",
  "gunma-shima-onsen": "kusatsu-town",
  "hakone-open-air-museum": "hakone-town",
  "hakone-shrine": "hakone-town",
  "hama-rikyu-gardens": "chuo-city-tokyo",
  "heian-jingu-shrine": "kyoto-city",
  "hida-folk-village": "takayama-city",
  "himeji-castle": "himeji-city",
  "hirado-castle-nagasaki": "nagasaki-city",
  "hirosaki-castle-park": "hirosaki-city",
  "hiroshima-peace-memorial-park": "hiroshima-city",
  "hiraizumi-chuson-ji": "morioka-city",
  "hitz-park-nagano": "nagano-city",
  "honmaru-palace": "nagoya-city",
  "hyogo-arima-onsen": "kobe-city",
  "hyogo-kinosaki-onsen": "toyooka-city",
  "inuyama-castle": "nagoya-city",
  "isewan-ferry-toba": "toba-city",
  "iwakuni-kintai-bridge": "hiroshima-city",
  "izumo-taisha-grand-shrine": "matsue-city",
  "izuno-mura": "narita-city",
  "jogasaki-coast": "ito-city",
  "jozenji-dori": "sendai-city",
  "katsura-imperial-villa": "kyoto-city",
  "kawagoe-warehouse-district": "kawagoe-city",
  "kawaichi-market-wajima": "wajima-city",
  "kibitsu-shrine": "okayama-city",
  "kinkaku-ji": "kyoto-city",
  "kinugawa-onsen": "nikko-city",
  "kiyo-mizu-dera": "kyoto-city",
  "kochi-castle": "kochi-city",
  "kofu-castle-park-yamanashi": "kofu-city",
  "koga-historical-museum": "koga-city",
  "koyasan-okunoin-cemetery": "wakayama-city",
  "kurashiki-bikan-historical-quarter": "okayama-city",
  "kushiro-marsh-national-park": "kushiro-city",
  "lake-tazawa-akita": "akita-city",
  "lake-towa-aomori": "aomori-city",
  "matsue-castle": "matsue-city",
  "matsushima-bay-miyagi": "sendai-city",
  "matsuyama-castle": "matsuyama-city",
  "miho-museum-shiga": "otsu-city",
  "minato-mirai-21": "yokohama-city",
  "mitoko-san-sanbutsu-ji": "tottori-city",
  "miwada-waterfall-yamanashi": "kofu-city",
  "miyajima-itsukushima-shrine": "hiroshima-city",
  "morioka-castle-site-park": "morioka-city",
  "mount-haguro-pagoda": "yamagata-city",
  "mount-hiei": "kyoto-city",
  "mount-ikoma-nara": "nara-city",
  "mount-iwaki-aomori": "hirosaki-city",
  "mount-koya": "wakayama-city",
  "mount-moiwa": "sapporo-city",
  "mount-mount-aso": "aso-city",
  "mount-rokko": "kobe-city",
  "mount-tsukuba-ibaraki": "tsukuba-city",
  "mount-unzen-nagasaki": "nagasaki-city",
  "nagano-kamikochi": "matsumoto-city",
  "nagano-narai-juku": "matsumoto-city",
  "nagano-suwa": "matsumoto-city",
  "nagano-tsumago-juku": "matsumoto-city",
  "nagasaki-peace-park": "nagasaki-city",
  "nagoya-castle": "nagoya-city",
  "naoshima-art-island": "takamatsu-city",
  "nara-park": "nara-city",
  "narita-san-shinsho-ji": "narita-city",
  "naruto-whirlpools": "tokushima-city",
  "nikko-tosho-gu": "nikko-city",
  "noboribetsu-jigokudani": "noboribetsu-city",
  "ogimachi-village-shirakawa-go": "takayama-city",
  "oishi-park-kawaguchiko": "fujikawaguchiko-town",
  "okayama-korakuen-garden": "okayama-city",
  "onomichi-temple-walk": "fukuyama-city",
  "osaka-castle-park": "osaka-city",
  "osu-kannon": "nagoya-city",
  "osu-shopping-district": "nagoya-city",
  "otaru-canal": "otaru-city",
  "ritsurin-garden": "takamatsu-city",
  "ryoan-ji-temple": "kyoto-city",
  "sado-island-niigata": "niigata-city",
  "saiho-ji-moss-temple": "kyoto-city",
  "sakurajima-volcano": "kagoshima-city",
  "sankei-en-garden": "yokohama-city",
  "sanzen-in-temple": "kyoto-city",
  "sapporo-clock-tower": "sapporo-city",
  "scmaglev-and-railway-park": "nagoya-city",
  "sendai-asaichi-morning-market": "sendai-city",
  "sendai-mediatheque": "sendai-city",
  "sendai-umino-mori-aquarium": "sendai-city",
  "shikotsuko-lake": "chitose-city",
  "shimane-iwami-ginzan": "matsue-city",
  "shimodate-museum-ibaraki": "tsukuba-city",
  "shimonoseki-karato-market": "shimonoseki-city",
  "shinjuku-gyo-en": "shinjuku-city",
  "shin-yokohama-ramen-museum": "yokohama-city",
  "shirin-park-nagano": "nagano-city",
  "shirakawa-go-historic-villages": "takayama-city",
  "shuzenji-onsen-izu": "izu-city",
  "takahashi-bitchu-matsuyama-castle": "okayama-city",
  "takahata-fudoson": "hachioji-tokyo",
  "takato-castle-nagano": "matsumoto-city",
  "takeda-castle-ruins-hyogo": "himeji-city",
  "takeda-castle-yamanashi": "kofu-city",
  "tanukikoji-shopping-street": "sapporo-city",
  "teshima-island-kagawa": "takamatsu-city",
  "todai-ji-temple": "nara-city",
  "togo-shrine-harajuku": "shibuya-city",
  "toki-messe-tower-niigata": "niigata-city",
  "tokyo-hinohara": "hachioji-tokyo",
  "tokyo-okutama": "ome-tokyo",
  "tottori-sand-dunes": "tottori-city",
  "tsunoshima-bridge-yamaguchi": "shimonoseki-city",
  "tsuruga-castle-fukushima": "aizuwakamatsu-city",
  "tsurugaoka-hachimangu": "kamakura-city",
  tsutenkaku: "osaka-city",
  "ueda-castle-nagano": "nagano-city",
  "ueno-park": "taito-city",
  "uji-tea-culture-center": "uji-city",
  "ukimido-mangetsu-ji": "otsu-city",
  "umeda-sky-building": "osaka-city",
  "universal-studios-japan": "osaka-city",
  "ushiku-daibutsu": "tsukuba-city",
  "utsunomiya-oya": "utsunomiya-city",
  "uwajima-castle": "matsuyama-city",
  "wakayama-castle": "wakayama-city",
  "yakushima-town": "kagoshima-city",
  "yamadera-yamagata": "yamagata-city",
  "yamanashi-fujiyoshida": "fujiyoshida-city",
  "yamanashi-nishizawa-valley": "kofu-city",
  "yamanashi-shosenkyo-gorge": "kofu-city",
  "yasaka-shrine": "kyoto-city",
  "yufu-city": "oita-city",
  "yugyo-ji": "fujisawa-city",
  "zao-fox-village-miyagi": "sendai-city",
  "zeniarai-benten": "kamakura-city",
  zuihoden: "sendai-city",
};

export const UNPARENTED_DESTINATION_IDS = [
  "ashigara",
  "boso-no-mura",
  "fukui",
  "gala-yuzawa",
  "kanazawa",
  "kanazawa-castle-ishikawa",
  "katori-jingu",
  "kiyotsu-gorge-niigata",
  "kurobe-gorge",
  "maruoka-castle-fukui",
  "mount-fuji",
  "noto",
  "ogasawara-islands-tokyo",
  "takaoka",
  "tojinbo-cliffs-fukui",
  "tomioka-silk-mill-gunma",
  "toyama-alpine",
] as const;

const REGION_OVERRIDES: Record<string, string> = {
  "shuri-castle-okinawa": "Okinawa",
};

const indexPath = path.join(
  process.cwd(),
  "src/shared/data/destinations-index.json",
);
const destinations = JSON.parse(
  fs.readFileSync(indexPath, "utf-8"),
) as Destination[];
const byId = new Map(
  destinations.map((destination) => [destination.id, destination]),
);

for (const [destinationId, parentId] of Object.entries(
  PARENT_BY_DESTINATION_ID,
)) {
  const destination = byId.get(destinationId);
  const parent = byId.get(parentId);
  if (destination && parent && parent.role === "hub") {
    destination.relationships = {
      ...destination.relationships,
      parentDestinationId: parentId,
    };
  }
}

for (const destinationId of UNPARENTED_DESTINATION_IDS) {
  const destination = byId.get(destinationId);
  if (destination && destination.relationships?.parentDestinationId) {
    delete destination.relationships.parentDestinationId;
    if (Object.keys(destination.relationships).length === 0) {
      delete destination.relationships;
    }
  }
}

for (const [destinationId, region] of Object.entries(REGION_OVERRIDES)) {
  const destination = byId.get(destinationId);
  if (destination) {
    destination.region = region;
  }
}

fs.writeFileSync(indexPath, `${JSON.stringify(destinations, null, 2)}\n`);
console.log(
  `Applied ${Object.keys(PARENT_BY_DESTINATION_ID).length} city-hub relationships to destinations index.`,
);
