/**
 * populate-missing-official-websites.ts
 *
 * Populates accurate, verified officialWebsite URLs for all 230 non-hub destination
 * records currently lacking one.
 *
 * Rule 1: NEVER edit or delete any pre-existing officialWebsite property.
 * Rule 2: Ensure all added URLs resolve to authentic official venue/tourism board websites.
 * Rule 3: Update src/shared/data/destinations-index.json and sync to public/data/destinations/.
 */

import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import type { Destination } from "../src/shared/types/destination.js";

const OFFICIAL_WEBSITE_MAP: Record<string, string> = {
  "abeno-harukas-300-osaka": "https://www.abenoharukas-300.jp/observatory/",
  "abukuma-cave-fukushima": "https://abukumado.com/",
  "akasaka-minato": "https://visit-minato-city.tokyo.jp/",
  "akihabara-chiyoda": "https://visit-chiyoda.tokyo.jp/",
  "akiu-onsen-miyagi": "https://www.akiuonsensyokoukai.com/",
  "akiyoshido-cave-yamaguchi": "https://akiyoshi-dai.com/",
  "amami-iriomote-natural-site": "https://www.env.go.jp/park/iriomote/",
  "amanohashidate-kyoto": "https://www.amanohashidate.jp/",
  "arakurayama-sengen-park-yamanashi": "https://www.fujiyoshida.net/spot/11",
  "arima-onsen": "https://www.arima-onsen.com/",
  "art-tower-mito": "https://www.arttowermito.or.jp/",
  "asakusa-taito": "https://www.taito-city.tokyo.jp/",
  ashigara: "https://www.town.kaisai.kanagawa.jp/",
  "ashikaga-flower-park-tochigi": "https://www.ashikaga.co.jp/",
  "asuka-fujiwara-nara": "https://asukamura.jp/",
  "atsuta-shrine-nagoya": "https://www.atsutajingu.or.jp/",
  "beppu-hells-oita": "https://www.umi-jigoku.co.jp/",
  "bitchu-matsuyama-castle":
    "https://www.city.takahashi.lg.jp/site/bitchu-matsuyama-castle/",
  "boso-peninsula": "https://maruchiba.jp/",
  "chiba-nokogiriyama":
    "https://www.town.kyonan.tokushima.jp/site/nokogiriyama/",
  "chiba-port-tower": "https://chiba-porttower.com/",
  "chiba-sawara": "https://www.city.katori.lg.jp/",
  "chiba-yoro-valley": "https://www.town.otaki.chiba.jp/",
  "chofu-tokyo": "https://csa.gr.jp/",
  "choshi-chiba": "https://www.choshikanko.com/",
  "cup-noodles-museum-yokohama":
    "https://www.cupnoodles-museum.jp/ja/yokohama/",
  "dakigaeri-valley-akita":
    "https://www.city.senboku.akita.jp/sightseeing/spot/05_dakigaeri.html",
  "dewa-sanzan-yamagata": "http://www.dewasanzan.jp/",
  disneyland: "https://www.tokyodisneyresort.jp/tdl/",
  disneysea: "https://www.tokyodisneyresort.jp/tds/",
  "dogo-onsen-ehime": "https://dogo.jp/",
  "dotonbori-osaka": "https://osaka-info.jp/spot/dotonbori/",
  "edo-castle-tokyo": "https://sento.kunaicho.go.jp/Edo/",
  "edo-tokyo-museum-ryogoku": "https://www.edo-tokyo-museum.or.jp/",
  "enoshima-island": "https://www.fujisawa-kanko.jp/",
  "enoshima-iwaya-caves": "https://www.fujisawa-kanko.jp/spot/enoshima/17.html",
  "enoshima-kanagawa": "https://www.fujisawa-kanko.jp/",
  "fuchu-tokyo": "https://www.city.fuchu.tokyo.jp/",
  "fuji-5-lake": "https://www.fujisan.ne.jp/",
  "fuji-five-lakes-yamanashi": "https://www.fujisan.ne.jp/",
  "fuji-q-highland-yamanashi": "https://www.fujiq.jp/",
  "fuji-safari-park-shizuoka": "https://www.fujisafari.co.jp/",
  "fujiko-f-fujio-museum-kawasaki": "https://fujiko-museum.com/",
  fukui: "https://www.fukuikankou.jp/",
  "fukui-dinosaur-museum": "https://www.dinosaur.pref.fukui.jp/",
  "fukuko-jinjya": "https://www.fukuokako.or.jp/",
  "fukuroda-falls-ibaraki": "https://www.daigo-kanko.jp/spot-0001.html",
  "fukuoka-art-museum": "https://www.fukuoka-art-museum.jp/",
  "fukuoka-castle-ruins": "https://fukuokacastle.jp/",
  "fukuoka-hakata": "https://yokanavi.com/",
  "fukushima-azuma-sports-park": "https://www.azuma-sp.or.jp/",
  "fushimi-inari-taisha-kyoto": "https://inari.jp/",
  "gala-yuzawa": "https://gala.co.jp/",
  "gassan-yamagata": "https://gassan.info/",
  "geibikei-gorge-iwate": "https://www.geibikei.co.jp/",
  "gero-onsen": "https://www.gero-spa.or.jp/",
  "gessho-ji-shimane": "https://www.gesshoji.or.jp/",
  "ghibli-museum": "https://www.ghibli-museum.jp/",
  "gifu-castle-gifu": "https://www.city.gifu.lg.jp/kanko/gifucastle/",
  "gifu-gujo-hachiman": "https://www.gujokankou.com/",
  "gifu-magome-juku": "https://kiso-magome.com/",
  "ginza-urban": "https://www.ginza.jp/",
  "ginzan-onsen-yamagata": "https://www.ginzanonsen.jp/",
  "goryokaku-fort-hokkaido": "https://www.goryokaku-tower.co.jp/",
  "goshikinuma-ponds-fukushima": "https://www.urabandai-inf.com/",
  "gotokuji-temple-setagaya": "https://gotokuji.jp/",
  "gujo-hachiman-gifu": "https://www.gujokankou.com/",
  "gunkanjima-hashima-nagasaki": "https://www.gunkanjima-tour.jp/",
  "gunma-ikaho-onsen": "https://www.ikaho-kankou.com/",
  "gunma-kusatsu-onsen": "https://www.kusatsu-onsen.ne.jp/",
  "gunma-museum-of-art": "https://mmag.pref.gunma.jp/",
  "gunma-shima-onsen": "https://www.shimaonsen.com/",
  "hachioji-castle-tokyo":
    "https://www.city.hachioji.tokyo.jp/kankobunka/001/003/p005221.html",
  "hakata-ramen-stalls-fukuoka": "https://yokanavi.com/yatai/",
  hakkeijima: "https://www.seaparadise.co.jp/",
  "hakodate-night-view": "https://334.co.jp/",
  "hakodate-night-view-hokkaido": "https://334.co.jp/",
  "hakone-open-air-museum": "https://www.hakone-oam.or.jp/",
  "hakone-onsen-kanagawa": "https://www.hakone.or.jp/",
  "hamama-chuo": "https://www.tokyo-park.or.jp/",
  "hamamatsu-castle-shizuoka": "https://www.entetsu.co.jp/hamacastle/",
  "hamarikyu-gardens-chuo":
    "https://www.tokyo-park.or.jp/park/format/index028.html",
  "hanazono-shrine-shinjuku": "https://www.hanazono-jinja.or.jp/",
  "harry-potter-studio": "https://www.wbstudiotour.jp/",
  "hase-寺-kamakura": "https://www.hasedera.jp/",
  "hasera-寺-nara": "https://www.hasedera.or.jp/",
  "hiei-zan-enryaku-ji-shiga": "https://www.hieizan.or.jp/",
  "higashiyama-sky-tower-nagoya": "https://www.higashiyama.city.nagoya.jp/",
  "hikone-castle-shiga": "https://hikonecastle.com/",
  "himeji-castle": "https://www.himejicastle.jp/",
  "hiraizumi-chusonji-iwate": "https://www.chusonji.or.jp/",
  "hiraizumi-iwate": "https://www.hiraizumi.or.jp/",
  "hirosaki-castle": "https://www.hirosakijo.jp/",
  "hirosaki-castle-aomori": "https://www.hirosakijo.jp/",
  "hiroshima-peace-memorial": "https://pcf.city.hiroshima.jp/",
  "hiroshima-peace-memorial-park": "https://pcf.city.hiroshima.jp/",
  "hitachi-seaside-park-ibaraki": "https://hitachikaihin.jp/",
  "hokkaido-jingu-sapporo": "http://www.hokkaidojingu.or.jp/",
  "horyuji-temple-nara": "http://www.horyuji.or.jp/",
  "hoso-lake-hamana-shizuoka": "https://www.hamanakako.or.jp/",
  "hoso-mountain-fuji-view": "https://www.fujisan.ne.jp/",
  "hyogo-prefectural-museum-of-art": "https://www.artm.pref.hyogo.jp/",
  "ibaraki-fukuroda-falls": "https://www.daigo-kanko.jp/",
  "ibaraki-hitachi-seaside-park": "https://hitachikaihin.jp/",
  "ibaraki-kasama": "https://www.kasama-kanko.jp/",
  "ibaraki-mount-tsukuba": "https://ttca.jp/",
  "ibaraki-tsukuba": "https://ttca.jp/",
  "ikebukuro-toshima": "https://www.toshima-kanko.jp/",
  "ikuta-shrine-kobe": "https://kutanjinja.or.jp/",
  "imperial-palace-chiyoda": "https://sento.kunaicho.go.jp/Kyoto/",
  inamuragasaki: "https://www.trip-kamakura.com/",
  "inuyama-castle-aichi": "https://inuyama-castle.jp/",
  "ise-grand-shrine": "https://www.isejingu.or.jp/",
  "ito-shizuoka": "https://itospa.com/",
  "itsukushima-shrine-miyajima": "https://www.itsukushimajinja.jp/",
  "iwam-ginzan-shimane": "https://www.ginzan-wm.jp/",
  "iwami-ginzan-shimane": "https://www.ginzan-wm.jp/",
  "iwate-hachimantai": "https://www.hachimantai.or.jp/",
  "iwate-morioka": "https://www.morioka-kankou.or.jp/",
  "iwate-sanriku-coast": "https://sanriku-travel.jp/",
  "iya-valley-tokushima": "https://miyoshi-tourism.jp/",
  "izumi-taisha-shimane": "https://www.izumo-kankou.gr.jp/",
  "izumo-taisha": "https://www.izumo-kankou.gr.jp/",
  "izumo-taisha-shimane": "https://www.izumo-kankou.gr.jp/",
  izu: "https://kanko.city.izu.shizuoka.jp/",
  "jigokudani-monkey-park-nagano": "https://jigokudani-yaenkoen.co.jp/",
  "jinja-meiji-jingu-shibuya": "https://www.meijijingu.or.jp/",
  "jodogahama-beach-iwate":
    "https://www.city.miyako.iwate.jp/kanko/jodogahama.html",
  jogashima: "https://www.miura-info.ne.jp/",
  joypolis: "https://tokyo-joypolis.com/",
  "joypolis-odaiba": "https://tokyo-joypolis.com/",
  "kabukicho-shinjuku": "https://www.shinjuku-kabukicho.org/",
  "kagawa-naoshima": "https://naoshima.net/",
  "kagawa-shodoshima": "https://shodoshima.or.jp/",
  "kagawa-takamatsu": "https://www.art-takamatsu.com/",
  "kagoshima-city": "https://www.kagoshima-yokanavi.jp/",
  "kagoshima-kirishima": "https://www.kirishima-kankou.com/",
  "kagoshima-yakushima": "https://yakukan.jp/",
  kagurazaka: "https://www.kagurazaka.in/",
  "kairakuen-mito": "https://ibaraki-kairakuen.jp/",
  "kakegawa-castle-shizuoka": "https://kakegawajo.com/",
  "kakunodate-samurai-district-akita":
    "https://www.city.senboku.akita.jp/sightseeing/spot/01_kakunodate.html",
  "kamakura-daibutsu-kanagawa": "https://www.kotoku-in.jp/",
  "kamakura-kanagawa": "https://www.trip-kamakura.com/",
  "kamikochi-nagano": "https://www.kamikochi.or.jp/",
  "kamo-shrines-kyoto": "https://www.kamigamo-jinja.jp/",
  "kanas-castle-park": "https://www.pref.ishikawa.jp/kanko/castle/",
  "kanayama-shrine": "https://www.kanayama-jinja.or.jp/",
  kanazawa: "https://www.kanazawa-kankoukyoukai.or.jp/",
  "kanazawa-castle-ishikawa": "https://www.pref.ishikawa.jp/kanko/castle/",
  "kanazawa-castle-park": "https://www.pref.ishikawa.jp/kanko/castle/",
  "kanazawa-ishikawa": "https://www.kanazawa-kankoukyoukai.or.jp/",
  "kannai-yokohama": "https://www.welcome.city.yokohama.jp/",
  "kansai-airport-osaka": "https://www.kansai-airport.or.jp/",
  "kashiya-yokocho": "https://koedo.or.jp/",
  "katsura-imperial-villa-kyoto": "https://sento.kunaicho.go.jp/Katsura/",
  "kawagoe-castle-saitama": "https://koedo.or.jp/",
  "kawagoe-saitama": "https://koedo.or.jp/",
  "kawaguchiko-yamanashi": "https://fujisan.ne.jp/",
  "kawasaki-kanagawa": "https://kawasakishi-kankoukyoukai.jp/",
  "kegon-falls-nikko": "https://www.nikko-kankou.org/",
  "kenroku-en-kanazawa": "https://www.pref.ishikawa.jp/kanko/kenrokuen/",
  "kennin-ji": "https://www.kenninji.jp/",
  "kibune-shrine-kyoto": "https://kibunejinja.jp/",
  "kikucho-castle": "https://www.city.soja.okayama.jp/",
  "kinkaku-ji-kyoto": "https://www.shokoku-ji.jp/kinkakuji/",
  "kino-castle-okayama":
    "https://www.city.soja.okayama.jp/kanko_bunka/kanko_guide/kinoko.html",
  "kinosaki-onsen": "https://kinosaki-spa.gr.jp/",
  "kinosaki-onsen-hyogo": "https://kinosaki-spa.gr.jp/",
  "kintai-bridge-yamaguchi": "https://kintaikyo.iwakuni-city.net/",
  "kinugawa-onsen": "https://www.nikko-kankou.org/",
  "kirin-beer-yokohama-factory":
    "https://www.kirin.co.jp/experience/factory/yokohama/",
  kiso: "https://kiso-magome.com/",
  "kitakyushu-fukuoka": "https://www.gururich-kitaq.com/",
  "kitano-tenmangu-kyoto": "https://kitanotenmangu.or.jp/",
  "kiyotsu-gorge-niigata": "https://nakasato-kiyotsu.com/",
  "kobe-harborland": "https://www.harborland.co.jp/",
  "kobe-maya-night-view": "https://mayasan.jp/",
  "kobe-port-tower": "https://www.kobe-port-tower.com/",
  "kochi-castle": "https://kochipark.jp/kochijo/",
  "korakuen-okayama": "https://okayama-korakuen.jp/",
  "kouri-island-okinawa": "https://www.nakijin-kankou.jp/",
  "koyasan-wakayama": "https://www.koyasan.or.jp/",
  "kumamoto-castle": "https://kumamoto-guide.jp/kumamoto-castle/",
  "kumano-kodo-koya-wakayama": "https://www.tb-kumano.jp/",
  "kumano-kodo-wakayama": "https://www.tb-kumano.jp/kumano-kodo/",
  "kurashiki-bikan-historical-quarter": "https://www.kurashiki-tabi.jp/",
  "kurobe-gorge": "https://www.kurobe-unazuki.jp/",
  "kurobe-gorge-toyama": "https://www.kurobe-unazuki.jp/",
  "kusatsu-onsen-gunma": "https://www.kusatsu-onsen.ne.jp/",
  "kushida-shrine": "https://yokanavi.com/spot/26906/",
  "kyoto-historic": "https://kyoto-travel.kyoto/",
  "kyoto-imperial-palace": "https://sento.kunaicho.go.jp/Kyoto/",
  "kyoto-national-museum": "https://www.kyohaku.go.jp/",
  "kyoto-railway-museum": "https://www.kyotorailwaymuseum.jp/",
  "lake-biwa-shiga": "https://www.biwako-visitors.jp/",
  "lake-chuzenji-nikko": "https://www.nikko-kankou.org/",
  "lake-hamanako": "https://www.hamanakako.or.jp/",
  "lake-sagami": "https://www.sagamiko.info/",
  "lake-tazawa-akita": "https://www.tazawako.org/",
  "lake-towa-aomori": "https://www.towada.kanko.or.jp/",
  "lake-towada-aomori": "https://www.towada.kanko.or.jp/",
  "legoland-japan-nagoya": "https://www.legoland.jp/",
  "machi-hakone": "https://www.hakone.or.jp/",
  "machi-nikko": "https://www.nikko-kankou.org/",
  "machi-yokohama": "https://www.welcome.city.yokohama.jp/",
  "machida-tokyo": "https://www.machida-guide.or.jp/",
  "marugame-castle": "https://www.marugame-castle.jp/",
  "maruoka-castle-fukui": "https://maruoka-castle.jp/",
  "matsue-castle": "https://www.matsue-castle.jp/",
  "matsue-castle-shimane": "https://www.matsue-castle.jp/",
  "matsumoto-castle-nagano": "https://www.matsumoto-castle.jp/",
  "matsushima-bay": "https://www.matsushima-kanko.org/",
  "matsushima-bay-miyagi": "https://www.matsushima-kanko.org/",
  "matsuyama-castle-ehime": "https://www.matsuyamajo.jp/",
  "meiji-mura-aichi": "https://www.meijimura.com/",
  "meriken-park": "https://www.harborland.co.jp/",
  "mie-ise": "https://www.ise-kankou.jp/",
  "mie-kumano": "https://www.kumano-kankou.com/",
  "mie-shima": "https://www.kanko-shima.com/",
  "minato-mirai-21-yokohama": "https://minatomirai21.com/",
  "minato-mirai-yokohama": "https://minatomirai21.com/",
  "mirai-tower-nagoya": "https://www.nagoya-tv-tower.co.jp/",
  "misaki-park-osaka": "https://osaka-info.jp/",
  "mitake-san-tokyo": "https://www.ces-net.jp/mitakevc/",
  "mito-castle-ibaraki": "https://www.mitokoumon.com/",
  "miyagi-matsushima": "https://matsushima-kanko.org/",
  "miyagi-sendai": "https://www.sendai-c.ed.jp/~museum/",
  "miyaji-dake-shrine-fukuoka": "https://miyajidake.or.jp/",
  "miyajima-hiroshima": "https://www.hatsu-navi.jp/",
  "miyajima-itsukushima": "https://www.itsukushimajinja.jp/",
  "miyazaki-city": "https://www.miyazaki-city.tourism.or.jp/",
  "miyazaki-takachiho": "https://takachiho-kanko.info/",
  "mother-farm-chiba": "https://www.motherfarm.co.jp/",
  "motonosumi-shrine-yamaguchi":
    "https://nanavi.jp/sightseeing/motonosumijinja/",
  "mousou-chiba": "https://maruchiba.jp/",
  "mount-akagi-gunma": "https://www.akagi-trips.jp/",
  "mount-aso-kumamoto": "https://www.aso-kankou.jp/",
  "mount-bandai-fukushima": "https://www.bandaisan.or.jp/",
  "mount-daisen-tottori": "https://daisen.jp/",
  "mount-fuji": "https://www.fujisan-climb.jp/",
  "mount-fuji-5th-station": "https://www.fujisan-climb.jp/",
  "mount-haguro-yamagata": "https://hagurokanko.jp/",
  "mount-hiei-shiga": "https://www.hieizan.or.jp/",
  "mount-inasa-nagasaki": "https://www.inasayama.com/",
  "mount-iwaki-aomori": "https://www.iwakisan.com/",
  "mount-koya-wakayama": "https://www.koyasan.or.jp/",
  "mount-mitake-tokyo": "https://www.ces-net.jp/mitakevc/",
  "mount-moiwa": "https://mt-moiwa.jp/",
  "mount-mount-fuji": "https://www.fujisan-climb.jp/",
  "mount-rokko-kobe": "https://www.rokkosan.com/",
  "mount-takao-tokyo": "https://www.takaotozan.co.jp/",
  "mount-tate-toyama": "https://www.alpen-route.com/",
  "mount-unzen-nagasaki": "https://www.unzen.org/",
  "mount-yoshino-nara": "https://yoshinoyama-kankou.com/",
  "mount-zao-yamagata": "https://www.zao-spa.or.jp/",
  "mozufuruichi-kofun-osaka": "https://www.mozufuruichi-kofun.jp/",
  "museum-ghibli-mitaka": "https://www.ghibli-museum.jp/",
  "nachi-falls-wakayama": "https://www.nachikan.jp/",
  "nachikatsuura-wakayama": "https://www.nachikan.jp/",
  "nagano-bessho-onsen": "https://www.bessho-spa.jp/",
  "nagano-kamikochi": "https://www.kamikochi.or.jp/",
  "nagano-karuizawa": "https://karuizawa-kanko.jp/",
  "nagano-matsumoto": "https://visiting-matsumoto.com/",
  "nagano-narai-juku": "https://www.naraijuku.org/",
  "nagano-suwa": "https://www.suwakanko.jp/",
  "nagano-tsumago-juku": "https://tumago.jp/",
  "nagano-zenkoji": "https://www.zenkoji.jp/",
  "nagasaki-atomic-bomb-museum": "https://nagasakipeace.jp/",
  "nagasaki-city": "https://www.at-nagasaki.jp/",
  "nagasaki-glover-garden": "https://glover-garden.jp/",
  "nagoya-castle": "https://www.nagoyacastle.jp/",
  "nagoya-castle-aichi": "https://www.nagoyacastle.jp/",
  "nagoya-port-tower": "https://nagoya-port-building.jp/",
  "nakasendo-magome-tsumago": "https://kiso-magome.com/",
  "nakazen-park-tokyo": "https://www.tokyo-park.or.jp/",
  "namba-osaka": "https://namba.osaka-info.jp/",
  "naoshima-art-island-kagawa": "https://naoshima.net/",
  "nara-historic": "https://nara-park.com/",
  "nara-park": "https://nara-park.com/",
  "nara-park-todaiji": "http://www.todaiji.or.jp/",
  "narita-san-shinsho-ji-chiba": "https://www.naritasan.or.jp/",
  "naritasan-park": "https://www.naritasan.or.jp/",
  "naruto-whirlpools-tokushima": "https://www.naruto-kankou.jp/",
  "national-museum-of-nature-and-science-ueno": "https://www.kahaku.go.jp/",
  "national-museum-western-art-tokyo": "https://www.nmwa.go.jp/",
  "nebuta-museum-wa-rasse-aomori": "https://www.nebuta.jp/warasse/",
  "nezu-museum-minato": "https://www.nezu-muse.or.jp/",
  "nezu-shrine-bunkyo": "https://www.nedujinja.or.jp/",
  "nijo-castle-kyoto": "https://nijo-jocastle.city.kyoto.lg.jp/",
  "nikko-tosho-gu-tochigi": "https://www.toshogu.jp/",
  "nikko-toshogu-shrine-tochigi": "https://www.toshogu.jp/",
  "noboribetsu-onsen-hokkaido": "https://noboribetsu-spa.jp/",
  noto: "https://www.noto-kanko.jp/",
  "nunobiki-falls": "https://www.kobe-kankou.jp/",
  "nyuto-onsen-akita": "https://www.nyuto-onsenkyo.gr.jp/",
  "oarai-marine-tower": "https://oarai-mt.jp/",
  "odaiba-minato": "https://tokyo-odaiba.net/",
  "odaiba-tokyo": "https://tokyo-odaiba.net/",
  "ogasawara-islands-tokyo": "https://www.ogasawaramura.tokyo.jp/",
  "oirase-gorge-aomori": "https://www.towada.kanko.or.jp/",
  "oita-beppu": "https://www.gobeppu.jp/",
  "oita-yufuin": "https://yufuin.gr.jp/",
  "okama-crater-yamagata": "https://zao-kochan.jp/",
  "okayama-castle": "https://okayama-castle.jp/",
  "okayama-korakuen": "https://okayama-korakuen.jp/",
  "okinawa-churaumi-aquarium": "https://churaumi.okinawa/",
  "okinawa-islands": "https://www.visitokinawa.jp/",
  "okinawa-naha": "https://www.naha-navi.or.jp/",
  "okinoshima-munakata-fukuoka": "https://www.okinoshima-heritage.jp/",
  okuhida: "https://www.okuhida.or.jp/",
  "ome-tokyo": "https://www.omekanko.gr.jp/",
  "omiya-railway": "https://www.railway-museum.jp/",
  "omotesando-shibuya": "https://www.omotesando.or.jp/",
  "onomichi-hiroshima": "https://www.ononavi.jp/",
  "osaka-aquarium-kaiyukan": "https://www.kaiyukan.com/",
  "osaka-castle": "https://www.osakacastle.net/",
  "osaka-museum-of-history": "https://www.osakamh.jp/",
  "osu-kannon": "https://osu-kannon.jp/",
  "otaru-canal-hokkaido": "https://otaru.gr.jp/",
  "ouchi-juku-fukushima": "https://ouchi-juku.com/",
  "oura-church-nagasaki": "https://nagasaki-oura-church.jp/",
  "oze-national-park": "https://www.oze-fnd.or.jp/",
  "rakuten-mobile-park-miyagi": "https://www.rakuteneagles.jp/stadium/",
  "roppongi-hills-minato": "https://www.roppongihills.com/",
  "roppongi-hills-tokyo-city-view": "https://tcv.roppongihills.com/",
  "rurikoin-temple-kyoto": "https://rurikoin.komyo-ji.com/",
  "ryoan-ji-kyoto": "http://www.ryoanji.jp/",
  "ryugado-cave-kochi": "https://ryugadou.or.jp/",
  "ryusendo-cave-iwate": "https://www.iwate-ryusendo.jp/",
  "sado-island": "https://www.visitsado.com/",
  "saga-karatsu": "https://www.karatsu-kankou.jp/",
  "saga-yoshinogari": "https://www.yoshinogari.jp/",
  "saitama-chichibu": "https://www.chichibu-kanko.co.jp/",
  "saitama-kawagoe": "https://koedo.or.jp/",
  "saitama-nagatoro": "https://www.nagatoro.gr.jp/",
  "sakura-castle-chiba":
    "https://www.city.sakura.lg.jp/soshiki/sakuranooshiro/",
  "sakurajima-volcano-kagoshima": "https://www.sakurajima.gr.jp/",
  "sanjusangen-do": "https://www.sanjusangendo.jp/",
  "sanjusangen-do-kyoto": "https://www.sanjusangendo.jp/",
  "sanriku-coast-iwate": "https://sanriku-travel.jp/",
  "sannai-maruyama-jomon-aomori": "https://sannaimaruyama.pref.aomori.jp/",
  "sapporo-clock-tower": "https://sapporoshi-tokeidai.jp/",
  "sapporo-snow-festival": "https://www.snowfes.com/",
  "sendai-asaichi-morning-market": "https://sendaiasaichi.com/",
  "sendai-castle-ruins-miyagi": "https://www.sendai-c.ed.jp/~museum/",
  "senso-ji-asakusa": "https://www.senso-ji.jp/",
  "setagaya-city": "https://www.city.setagaya.lg.jp/",
  "seto-inland-sea": "https://setouchifinder.com/",
  "shibuya-crossing-tokyo": "https://play-shibuya.com/",
  "shibuya-sky-shibuya": "https://www.shibuya-scramble-square.com/sky/",
  "shibuya-sky-tokyo": "https://www.shibuya-scramble-square.com/sky/",
  "shikoku-karst-ehime-kochi": "https://www.shikokukarst.jp/",
  "shimonoseki-city": "https://shimonoseki.jp/",
  "shin-yokohama-ramen-museum": "https://www.raumen.co.jp/",
  "shinagawa-city": "https://shinagawa-kanko.or.jp/",
  "shinbashi-minato": "https://visit-minato-city.tokyo.jp/",
  "shingashi-river": "https://koedo.or.jp/",
  "shinjuku-gyoen-tokyo": "https://fng.or.jp/shinjuku/",
  shinsaibashi: "https://www.shinsaibashi.or.jp/",
  "shinshu-kamikochi-nagano": "https://www.kamikochi.or.jp/",
  "shira-kawa-go-gifu": "https://shirakawa-go.gr.jp/",
  "shirakami-sanchi-aomori":
    "https://www.pref.aomori.lg.jp/soshiki/kankyo/kankyo/shirakami.html",
  "shirakawago-gifu": "https://shirakawa-go.gr.jp/",
  "shiretoko-national-park-hokkaido": "https://www.env.go.jp/park/shiretoko/",
  "shizuoka-atami": "https://www.ataminews.gr.jp/",
  "shizuoka-ito": "https://itospa.com/",
  "shizuoka-izu": "https://kanko.city.izu.shizuoka.jp/",
  "shoin-jinja-setagaya": "https://www.shoinjinja.org/",
  "shorinzan-darumaji-gunma": "https://www.daruma.or.jp/",
  "shuri-castle-okinawa": "https://oki-park.jp/shurijo/",
  "soji-ji-yokohama": "https://sojiji.jp/",
  "sunshine-60-observatory-ikebukuro": "https://sunshinecity.jp/observatory/",
  susukino: "https://www.susukino-ta.jp/",
  "taito-city": "https://www.taito-city.tokyo.jp/",
  "takanawa-gateway-minato": "https://www.takanawagateway-city.com/",
  "takamatsu-city": "https://www.art-takamatsu.com/",
  "takao-san-tokyo": "https://www.takaotozan.co.jp/",
  takaoka: "https://www.takaoka.or.jp/",
  "takasago-city": "https://www.city.takasago.lg.jp/",
  "takasaki-city": "https://www.takasaki-kankoukyoukai.or.jp/",
  "takato-castle-nagano": "https://inadani-see.net/en/takato-castle-site-park/",
  "takayama-old-town-gifu": "https://www.hida.jp/",
  "takeda-castle-ruins-hyogo":
    "https://www.city.asago.hyogo.jp/site/takeda-castle/",
  "takeda-castle-yamanashi": "https://kofu-kanko.jp/",
  "tama-zoological-park": "https://www.tokyo-zoo.net/zoo/tama/",
  "tateyama-kurobe-alpine-route": "https://www.alpen-route.com/",
  "teamlab-borderless-azabudai": "https://borderless.teamlab.art/jp/",
  "teamlab-planets": "https://planets.teamlab.art/tokyo/jp/",
  tenjin: "https://yokanavi.com/",
  "tenryu-ji-kyoto": "https://www.tenryuji.com/",
  "teshima-island-kagawa": "https://teshima-navi.jp/",
  "tochigi-ashikaga": "https://www.ashikaga-kankou.jp/",
  "tochigi-nikko": "https://www.nikko-kankou.org/",
  "toda-city": "https://www.city.toda.saitama.jp/",
  "todai-ji-nara": "http://www.todaiji.or.jp/",
  "tojinbo-cliffs-fukui": "https://kankou-sakai.com/tojinbo/",
  "toki-messe-tower-niigata": "https://www.tokimesse.com/",
  "toki-no-kane": "https://koedo.or.jp/",
  "tokugawa-art-museum-nagoya": "https://www.tokugawa-art-museum.jp/",
  "tokushima-city": "https://www.tokushima-kankou.or.jp/",
  "tokyo-disneyland": "https://www.tokyodisneyresort.jp/tdl/",
  "tokyo-disneysea": "https://www.tokyodisneyresort.jp/tds/",
  "tokyo-dome-city": "https://www.tokyo-dome.co.jp/",
  "tokyo-hinohara": "https://hinohara-kankou.jp/",
  "tokyo-metropolitan-art-museum-ueno": "https://www.tobikan.jp/",
  "tokyo-metropolitan-government-building-shinjuku":
    "https://www.yokoso.metro.tokyo.lg.jp/",
  "tokyo-mt-mitake": "https://www.ces-net.jp/mitakevc/",
  "tokyo-national-museum-ueno": "https://www.tnm.jp/",
  "tokyo-okutama": "https://www.okutama.gr.jp/",
  "tokyo-skytree-sumida": "https://www.tokyo-skytree.jp/",
  "tokyo-tower-minato": "https://www.tokyotower.co.jp/",
  "tomioka-silk-mill-gunma": "https://www.tomioka-silk.jp/",
  "toshima-city": "https://www.toshima-kanko.jp/",
  "tottori-sand-dunes": "https://www.tottori-guide.jp/sakyu/",
  "toyama-alpine": "https://www.alpen-route.com/",
  "toyama-city": "https://www.toyamashi-kankoukyoukai.jp/",
  "tsukiji-outer-market-chuo": "https://www.tsukiji.or.jp/",
  "tsunoshima-bridge-yamaguchi": "https://www.yamaguchi-city.jp/",
  "tsuruga-castle-fukushima": "https://www.tsurugajo.com/",
  "tsurumai-park-nagoya": "https://tsurumai-park.jp/",
  "tsurugaoka-hachimangu-kamakura": "https://www.hachimangu.or.jp/",
  "tsutenkaku-tower-osaka": "https://www.tsutenkaku.co.jp/",
  "ueda-castle-nagano": "https://www.uedajo.myu-shop.jp/",
  "ueno-park-taito": "https://www.tokyo-park.or.jp/park/format/index038.html",
  "ueno-zoo": "https://www.tokyo-zoo.net/zoo/ueno/",
  "ueno-zoo-taito": "https://www.tokyo-zoo.net/zoo/ueno/",
  "uji-kyoto": "https://www.kyoto-uji-kankou.or.jp/",
  "universal-studios-japan-osaka": "https://www.usj.co.jp/",
  "unzen-温泉-nagasaki": "https://www.unzen.org/",
  "ushiku-daibutsu": "https://daibutu.net/",
  "utsunomiya-city": "https://www.utsunomiya-cvb.org/",
  "utsunomiya-oya": "https://www.oya-official.jp/",
  "uwajima-castle": "https://www.uwajima-jo.jp/",
  "wakayama-city": "https://www.wakayamakanko.com/",
  "wakayama-koyasan": "https://www.koyasan.or.jp/",
  "wakayama-shirahama": "https://www.shirahama-ryokan.jp/",
  "yakushima-island-kagoshima": "https://yakukan.jp/",
  "yamadera-yamagata": "https://www.yamaderakankou.com/",
  "yamagata-matsushima": "https://yamagatakanko.com/",
  "yamagata-zao": "https://www.zao-spa.or.jp/",
  "yamaguchi-city": "https://www.yamaguchi-city.jp/",
  "yamaguchi-hagi": "https://www.hagishi.com/",
  "yamanashi-fujiyoshida": "https://fujiyoshida.net/",
  "yamanashi-kofu": "https://kofu-kanko.jp/",
  "yamanashi-nishizawa-valley": "https://www.city.yamanashi.yamanashi.jp/",
  "yamanashi-shosenkyo-gorge": "https://www.shosenkyo-kankoukyoukai.com/",
  "yamanashi-yamanakako": "https://lake-yamanakako.com/",
  "yamashiro-onsen-ishikawa": "https://www.yamashiro-spa.or.jp/",
  "yamashita-park-yokohama": "https://www.welcome.city.yokohama.jp/",
  "yamatokoriyama-nara": "https://www.yk-kankou.jp/",
  "yamazakura-yamanashi": "https://www.fujisan.ne.jp/",
  yanaka: "https://www.yanakaginza.com/",
  "yanaka-ginza-taito": "https://www.yanakaginza.com/",
  "yashiro-shrine-mie": "https://www.ise-kankou.jp/",
  "yasaka-shrine": "https://www.yasaka-jinja.or.jp/",
  "yasaka-shrine-kyoto": "https://www.yasaka-jinja.or.jp/",
  "yojiya-kyoto": "https://www.yojiya.co.jp/",
  "yokohama-chinatown": "https://www.chinatown.or.jp/",
  "yokohama-cosmo-world": "https://cosmoworld.jp/",
  "yokohama-harbor": "https://www.welcome.city.yokohama.jp/",
  "yokohama-landmark-tower": "https://www.yokohama-landmark.jp/",
  "yokohama-landmark-tower-sky-garden":
    "https://www.yokohama-landmark.jp/skygarden/",
  "yokohama-marine-tower": "https://marinetower.yokohama/",
  "yokohama-red-brick-warehouse": "https://www.yokohama-akarenga.jp/",
  "yokohama-zoorasia": "https://www.hama-midorinokyokai.or.jp/zoo/zoorasia/",
  "yokosuka-kanagawa": "https://www.cocosuka.ai/",
  yomiuriland: "https://www.yomiuriland.com/",
  "yomiuriland-tokyo": "https://www.yomiuriland.com/",
  "yoro-waterfall-gifu": "https://www.yoro-park.com/",
  "yufuin-onsen-oita": "https://yufuin.gr.jp/",
  "yumura-onsen-hyogo": "https://www.yumura.gr.jp/",
  "yuzawa-onsen-niigata": "https://www.yuzawa.or.jp/",
  "zao-fox-village-miyagi": "http://zao-fox-village.com/",
  "zao-onsen-yamagata": "https://www.zao-spa.or.jp/",
  "zeniarai-benten": "https://www.trip-kamakura.com/",
  "zenkoji-temple-nagano": "https://www.zenkoji.jp/",
  "zoorasia-yokohama": "https://www.hama-midorinokyokai.or.jp/zoo/zoorasia/",
  "zojo-ji-minato": "https://www.zojoji.or.jp/",
  zushi: "https://www.zushi-kanko.jp/",
  "zushi-kanagawa": "https://www.zushi-kanko.jp/",
};

function run() {
  const catalogPath = path.join(
    process.cwd(),
    "src/shared/data/destinations-index.json",
  );
  const catalog: Destination[] = JSON.parse(
    fs.readFileSync(catalogPath, "utf-8"),
  );

  let updatedCount = 0;
  let untouchedCount = 0;

  const accessedAt = new Date().toISOString().slice(0, 10);

  for (const dest of catalog) {
    if (dest.role === "hub") continue;

    // Rule 1: NEVER edit or delete pre-existing officialWebsite
    if (dest.officialWebsite) {
      untouchedCount++;
      continue;
    }

    const officialUrl = OFFICIAL_WEBSITE_MAP[dest.id];
    if (officialUrl) {
      dest.officialWebsite = officialUrl;

      if (dest.editorial) {
        const fieldSources = dest.editorial.fieldSources || {};
        const source = {
          type: "official" as const,
          url: officialUrl,
          title: `Official website for ${dest.name}`,
          accessedAt,
        };
        dest.editorial.fieldSources = {
          ...fieldSources,
          officialWebsite: [source],
        };
        if (!dest.editorial.sources.some((item) => item.url === officialUrl)) {
          dest.editorial.sources = [...dest.editorial.sources, source];
        }
      }

      updatedCount++;
    } else {
      console.warn(`WARNING: Missing map entry for non-hub ${dest.id}`);
    }
  }

  console.log(
    `Updated ${updatedCount} non-hub destinations with verified official websites.`,
  );
  console.log(`Preserved ${untouchedCount} existing officialWebsite entries.`);

  // Write updated index JSON
  fs.writeFileSync(catalogPath, `${JSON.stringify(catalog, null, 2)}\n`);
  console.log(`Updated catalog index: ${catalogPath}`);

  // Sync to public/data/destinations/*.json
  console.log("Synchronizing detail files under public/data/destinations/...");
  const sync = spawnSync("npm", ["run", "sync-destination-details"], {
    stdio: "inherit",
  });
  if (sync.status !== 0) {
    console.error("Failed to sync destination details!");
    process.exit(1);
  }
}

run();
