/**
 * Cloudflare Pages Function: /destinations/[id]
 *
 * KAI-68: serves prerendered HTML for published destinations, the SPA shell
 * for other public destinations, and a real 404 (noindex) for unknown or
 * removed destination ids. Pages Functions take precedence over _redirects,
 * so the `/* /index.html 200` fallback never masks the 404.
 *
 * _routes.json include: ["/destinations/*"] — only this route invokes the
 * function; everything else stays static.
 *
 * The manifest (dist/data/kai68-public-destinations.json) is generated by
 * scripts/generate-seo-outputs.ts from the same catalogue the SPA loads, so
 * function and app always agree on what is public.
 *
 * Note: _headers does NOT apply to Function responses; SECURITY headers are
 * set here (see src/seo/meta.ts) and must be kept in sync with public/_headers.
 */
import { routeDestinationRequest } from "../../src/seo/router.js";
import { SECURITY_HEADERS } from "../../src/seo/meta.js";

const MANIFEST_PATH = "/data/kai68-public-destinations.json";

let manifestCache = null;

async function loadManifest(env) {
  if (manifestCache) return manifestCache;
  const response = await env.ASSETS.fetch(MANIFEST_PATH);
  if (!response.ok) return null;
  manifestCache = await response.json();
  return manifestCache;
}

export async function onRequest(context) {
  const { id } = context.params;
  if (typeof id !== "string" || !/^[a-z0-9-]{1,128}$/.test(id)) {
    return new Response("Not Found", {
      status: 404,
      headers: SECURITY_HEADERS,
    });
  }

  const manifest = await loadManifest(context.env);
  if (!manifest) {
    // Manifest missing: fail open to the SPA shell so valid destinations
    // keep working even if the build step was skipped.
    const shell = await context.env.ASSETS.fetch("/index.html");
    return new Response(shell.body, {
      status: 200,
      headers: {
        ...SECURITY_HEADERS,
        "Content-Type": "text/html; charset=utf-8",
      },
    });
  }

  const result = await routeDestinationRequest({
    id,
    manifest,
    fetchAsset: (path) => context.env.ASSETS.fetch(path),
  });

  const baseHeaders = {
    ...SECURITY_HEADERS,
    ...result.headers,
  };

  if (result.body !== undefined) {
    return new Response(result.body, {
      status: result.status,
      headers: {
        ...baseHeaders,
        "Content-Type": "text/html; charset=utf-8",
      },
    });
  }

  const asset = await context.env.ASSETS.fetch(result.assetPath);
  return new Response(asset.body, {
    status: result.status,
    headers: {
      ...baseHeaders,
      "Content-Type": "text/html; charset=utf-8",
    },
  });
}
