name: PR Title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read

jobs:
  validate-title:
    name: validate-title
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR Title Prefix
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "$PR_TITLE" | grep -Eq \
            '^(feat|fix|data|refactor|test|docs|chore|release|hotfix): .+'
